### ISSUE TITLE
Adapt Serial to Parallel Port

### ISSUE THREAD

**Issue by marcelfarres** [tarm/serial#25]
During the past month I tried to adapt go serial to read/write to a parallel port unsuccessfully in order to perform an online EEG study.

I'm running windows 7, Do you have some clues how to make it work? 

Thanks!

PD: I can do a fork and upload the code if you want :)

**Comment by tarm** [comment]
I think parallel ports are different enough (and much less common) that it does not makes sense to support them in the standard tarm/serial library.

Feel free to fork tarm/serial as a starting point for your parallel port work if that makes sense for you.
