### ISSUE TITLE
Windows ReadTimeout no effect

### ISSUE THREAD

**Issue by MiyamuraMiyako** [tarm/serial#81]
when serial readbuffer haven't any data. ```Read``` return immediately, not wait setting's timeout.

**Comment by MiyamuraMiyako** [comment]
Just simple code. @xiegeo 

```go
sc := &serial.Config{Name: "COM3", Baud: 9600, Size: 8, Parity: serial.ParityNone, StopBits: serial.Stop1, ReadTimeout: time.Millisecond * 50}
sp, err := serial.OpenPort(sc)
if err != nil {
	fmt.Println(err.Error())
	return false
}
buf := make([]byte, 128)
sp.Read(buf)
return true
```

**Comment by xiegeo** [comment]
50 milliseconds is very short, so it's unlikely to catch anything before timing out.

Also, your read doesn't do anything, you should check for errors and the number returned to know if you have read any data. 

As your code is written,  your behavior is expected.

**Comment by MiyamuraMiyako** [comment]
@xiegeo sorry,My mistake.
